"""initial research persistence

Revision ID: 338255031ae5
Revises:
Create Date: 2026-09-15 19:30:09.136256
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '338255031ae5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('ticker', name='uq_companies_ticker')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('filings',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('filing_type', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_filings_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filings')),
    sa.UniqueConstraint('accession_number', name='uq_filings_accession_number')
    )
    op.create_index('ix_filings_company_filing_date', 'filings', ['company_id', 'filing_date'], unique=False)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_index('ix_filings_ticker_filing_date', 'filings', ['ticker', 'filing_date'], unique=False)
    op.create_table('research_tasks',
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('include_sec_research', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='researchtaskstatus', native_enum=False, length=16), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_research_tasks_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_tasks'))
    )
    op.create_index('ix_research_tasks_company_created_at', 'research_tasks', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_tasks_company_id'), 'research_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_request_id'), 'research_tasks', ['request_id'], unique=False)
    op.create_index('ix_research_tasks_status_created_at', 'research_tasks', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_tasks_ticker'), 'research_tasks', ['ticker'], unique=False)
    op.create_table('research_reports',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_research_reports_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['research_tasks.id'], name=op.f('fk_research_reports_task_id_research_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_reports')),
    sa.UniqueConstraint('task_id', name='uq_research_reports_task_id')
    )
    op.create_index('ix_research_reports_company_generated_at', 'research_reports', ['company_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_research_reports_company_id'), 'research_reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_reports_ticker'), 'research_reports', ['ticker'], unique=False)
    op.create_index('ix_research_reports_ticker_generated_at', 'research_reports', ['ticker', 'generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_research_reports_ticker_generated_at', table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_ticker'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_company_id'), table_name='research_reports')
    op.drop_index('ix_research_reports_company_generated_at', table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_research_tasks_ticker'), table_name='research_tasks')
    op.drop_index('ix_research_tasks_status_created_at', table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_request_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_company_id'), table_name='research_tasks')
    op.drop_index('ix_research_tasks_company_created_at', table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index('ix_filings_ticker_filing_date', table_name='filings')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index('ix_filings_company_filing_date', table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
